"""Byte-identical parity with the Presidio implementation this replaced.

`tests/corpus/parity-v1.json` was generated by `scripts/build_parity_corpus.py`
against the previous detector. It records the exact findings and redacted text
for 475 adversarial cases. PRD-02 required identical detection results; this is
the test that proves it, and the 27-case `guard-v1` corpus is far too small to.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

import pytest

from shim_guard.guard import evaluate

CORPUS = Path(__file__).resolve().parents[1] / "corpus" / "parity-v1.json"
GENERATOR = Path(__file__).resolve().parents[2] / "scripts" / "build_parity_corpus.py"


def _document() -> dict:
    return json.loads(CORPUS.read_text(encoding="utf-8"))


def _generator() -> ModuleType:
    specification = importlib.util.spec_from_file_location(
        "shim_parity_generator", GENERATOR
    )
    assert specification and specification.loader
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


_DOCUMENT = _document()
_CASES = _DOCUMENT["cases"]


def test_the_frozen_corpus_is_substantial() -> None:
    assert _DOCUMENT["case_count"] == len(_CASES) >= 400
    assert sum(len(case["findings"]) for case in _CASES) >= 300
    assert len({case["id"] for case in _CASES}) == len(_CASES)


def test_the_generator_still_produces_the_frozen_inputs() -> None:
    """A drifted generator would silently shrink the safety net."""
    generated = _generator().cases()
    assert [(identifier, text) for identifier, text in generated] == [
        (case["id"], case["text"]) for case in _CASES
    ]


@pytest.mark.parametrize("case", _CASES, ids=lambda case: case["id"])
def test_detection_is_unchanged(case: dict) -> None:
    decision = evaluate(case["text"])
    actual = [
        [finding.entity_type, finding.start, finding.end, finding.score]
        for finding in decision.findings
    ]
    assert actual == case["findings"], (
        f"findings changed for {case['id']!r}\n"
        f"  text     : {case['text'][:120]!r}\n"
        f"  expected : {case['findings']}\n"
        f"  actual   : {actual}"
    )
    assert decision.redacted_text == case["redacted"], (
        f"redaction changed for {case['id']!r}\n"
        f"  expected : {case['redacted'][:200]!r}\n"
        f"  actual   : {decision.redacted_text[:200]!r}"
    )
