"""Generate the frozen public suffix table used by the email recognizer.

The detector must decide whether an email host ends in a real public suffix
without reading the network or the filesystem, so the ICANN section of the
Public Suffix List is compiled into a Python module as one string literal.
Punycode forms are precomputed here, which is what lets the runtime lookup be a
plain set membership test with no IDNA decoding on the hook path.

Run against any `public_suffix_list.dat`, including the snapshot bundled with
tldextract:

    python scripts/build_suffix_list.py \
        --snapshot .venv/lib/python3.13/site-packages/tldextract/.tld_set_snapshot \
        --output src/shim_guard/guard/suffixes.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = '''"""Frozen ICANN public suffix table.

Generated by ``scripts/build_suffix_list.py``; do not edit by hand. Only the
ICANN section is included, matching ``include_psl_private_domains=False`` in
the tldextract configuration this replaces, so entries such as ``blogspot.com``
are deliberately absent and remain registrable.

Source: {source}
Entries: {count} ({wildcards} wildcard, {exceptions} exception)
"""

from __future__ import annotations

SOURCE = {source!r}

_RULES = """\\
{blob}"""

_SUFFIXES = frozenset(_RULES.split("\\n"))


def public_suffix(host: str) -> str:
    """Return the longest public suffix of ``host``, or an empty string."""
    labels = host.split(".")
    for index in range(len(labels)):
        candidate = ".".join(labels[index:])
        if "!" + candidate in _SUFFIXES:
            return ".".join(labels[index + 1 :])
        if candidate in _SUFFIXES:
            return candidate
        if index and "*." + ".".join(labels[index:]) in _SUFFIXES:
            return ".".join(labels[index - 1 :])
    return ""


def is_registrable(host: str) -> bool:
    """Return whether ``host`` is a registrable name under a public suffix.

    This reproduces ``bool(extract(host).fqdn and extract(host).suffix)``: the
    host must end in a public suffix and carry at least one label in front of
    it. ``example.com`` is registrable; ``co.uk`` and ``example.invalid`` are
    not.
    """
    normalized = host.lower().rstrip(".")
    if not normalized or "" in normalized.split("."):
        return False
    suffix = public_suffix(normalized)
    if not suffix or suffix == normalized:
        return False
    return bool(normalized[: -len(suffix) - 1])
'''


def punycode(suffix: str) -> str:
    """Return the all-ASCII form of ``suffix``, or the input when unchanged."""
    labels = []
    for label in suffix.split("."):
        if label.isascii():
            labels.append(label)
            continue
        labels.append(label.encode("idna").decode("ascii"))
    return ".".join(labels)


def icann_rules(snapshot: str) -> list[str]:
    """Return the ICANN section rules, with punycode variants added."""
    rules: set[str] = set()
    private = False
    for line in snapshot.splitlines():
        text = line.strip()
        if text.startswith("// ===BEGIN PRIVATE DOMAINS==="):
            private = True
            continue
        if text.startswith("// ===END PRIVATE DOMAINS==="):
            private = False
            continue
        if private or not text or text.startswith("//"):
            continue
        rules.add(text)
        marker = ""
        body = text
        if text[0] in "*!":
            marker, body = text[0], text[2:] if text[1] == "." else text[1:]
            marker = text[:2] if text[1] == "." else text[0]
        try:
            ascii_form = punycode(body)
        except UnicodeError:
            continue
        if ascii_form != body:
            rules.add(marker + ascii_form)
    return sorted(rules)


def render(rules: list[str], source: str) -> str:
    """Return the generated module text."""
    if any('"' in rule or "\\" in rule for rule in rules):
        raise ValueError("a suffix rule would break the string literal")
    return HEADER.format(
        source=source,
        count=len(rules),
        wildcards=sum(1 for rule in rules if rule.startswith("*")),
        exceptions=sum(1 for rule in rules if rule.startswith("!")),
        blob="\n".join(rules),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--source", default="")
    args = parser.parse_args()
    rules = icann_rules(args.snapshot.read_text(encoding="utf-8"))
    source = args.source or f"publicsuffix.org ICANN section, via {args.snapshot.name}"
    args.output.write_text(render(rules, source), encoding="utf-8")
    print(f"{len(rules)} rules -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
